# Fly.io — deploy: docs/DEPLOY.md
# App name: altere se necessário ou use fly launch --name SEU_NOME

app = 'distributed-chat-teste'
primary_region = 'gru'

[build]
  dockerfile = 'Dockerfile'

[env]
  ENABLE_TCP_SERVER = 'false'
  HISTORY_MAX = '500'
  PUBSUB_CHANNEL = 'chat:broadcast'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
